In [ ]:
import torch

# From a list
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(t1)

# Pre-filled tensors
zeros = torch.zeros(3, 3)
ones = torch.ones(2, 4)
rand = torch.rand(2, 2)          # uniform random [0,1)
identity = torch.eye(3)          # identity matrix
print(zeros, ones, rand, identity)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]) tensor([[0.1230, 0.3967],
        [0.6379, 0.0562]]) tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
t = torch.arange(12).reshape(3, 4)
print(t)

print(t[0])          # first row
print(t[:, 1])       # second column
print(t[1, 2])       # single element
print(t[0:2, 1:3])   # sub-matrix slice

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([1, 5, 9])
tensor(6)
tensor([[1, 2],
        [5, 6]])


In [ ]:
t = torch.arange(12)
print(t.view(3, 4))       # reshape into 3x4
print(t.reshape(4, 3))    # reshape into 4x3
print(t.view(2, -1))      # -1 lets PyTorch infer the size

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


In [ ]:
a = torch.rand(2, 3)
b = torch.rand(3, 4)

c1 = torch.matmul(a, b)
c2 = a @ b               # same thing, shorthand operator
print(c1.shape)          # should be (2, 4)

# Element-wise multiplication (NOT matrix mult) for contrast
d = torch.rand(2, 3)
e = torch.rand(2, 3)
elementwise = d * e
print(elementwise.shape) # (2, 3)

torch.Size([2, 4])
torch.Size([2, 3])


In [ ]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])   # shape (2,3)
b = torch.tensor([10, 20, 30])              # shape (3,)

result = a + b   # b is "broadcast" across each row
print(result)

tensor([[11, 22, 33],
        [14, 25, 36]])


In [ ]:
t = torch.rand(3, 4)

print(t.sum())            # sum of all elements
print(t.sum(dim=0))       # sum down each column
print(t.sum(dim=1))       # sum across each row
print(t.mean())
print(t.max())
print(t.max(dim=1))       # returns both max values AND their indices

tensor(6.4024)
tensor([1.3928, 2.5142, 1.6200, 0.8754])
tensor([1.6820, 2.4053, 2.3151])
tensor(0.5335)
tensor(0.9765)
torch.return_types.max(
values=tensor([0.7798, 0.9765, 0.9232]),
indices=tensor([1, 0, 2]))


In [ ]:
if torch.cuda.is_available():
    t_cpu = torch.rand(1000, 1000)
    t_gpu = t_cpu.to('cuda')
    print("On GPU:", t_gpu.device)

    # Compare speed
    import time
    start = time.time()
    _ = t_cpu @ t_cpu
    print("CPU time:", time.time() - start)

    start = time.time()
    _ = t_gpu @ t_gpu
    torch.cuda.synchronize()
    print("GPU time:", time.time() - start)
else:
    print("No GPU available in this runtime")

No GPU available in this runtime
